name: Club Brugge Sector Checker

on:
  schedule:
    - cron: "* * * * *"  # every minute
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run sector check
        run: ./check-sectors.sh
        env:
          HC_PING: ${{ secrets.HC_PING }}
